"""add saved trips

Revision ID: 5e0231b8eae6
Revises: d708769649c7
Create Date: 2026-09-02 19:29:01.763837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0231b8eae6'
down_revision = 'd708769649c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('travel_style', sa.String(length=20), nullable=False),
    sa.Column('display_currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_user_id'), ['user_id'], unique=False)

    op.create_table('trip_stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('daily_cost_gbp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hostel_per_night_gbp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('living_per_day_gbp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'position', name='uq_trip_stop_position')
    )
    with op.batch_alter_table('trip_stop', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_stop_city_id'), ['city_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trip_stop_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_stop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_stop_trip_id'))
        batch_op.drop_index(batch_op.f('ix_trip_stop_city_id'))

    op.drop_table('trip_stop')
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_user_id'))

    op.drop_table('trip')
    # ### end Alembic commands ###
