"""add sharable trips

Revision ID: 8a0be992e9af
Revises: 5e0231b8eae6
Create Date: 2026-09-03 13:05:41.310038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0be992e9af'
down_revision = '5e0231b8eae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.create_index(batch_op.f('ix_trip_share_token'), ['share_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_share_token'))
        batch_op.drop_column('is_public')
        batch_op.drop_column('share_token')

    # ### end Alembic commands ###
