"""add trip transport costs

Revision ID: faa27366f923
Revises: 8a0be992e9af
Create Date: 2026-09-03 15:09:57.625821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa27366f923'
down_revision = '8a0be992e9af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_leg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('from_city_id', sa.Integer(), nullable=False),
    sa.Column('to_city_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('cost_gbp', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['from_city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['to_city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'position', name='uq_trip_leg_position')
    )
    with op.batch_alter_table('trip_leg', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_leg_from_city_id'), ['from_city_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trip_leg_to_city_id'), ['to_city_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trip_leg_trip_id'), ['trip_id'], unique=False)

    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arrival_transport_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('arrival_transport_cost_gbp', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('arrival_transport_note', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('departure_transport_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('departure_transport_cost_gbp', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('departure_transport_note', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('departure_transport_note')
        batch_op.drop_column('departure_transport_cost_gbp')
        batch_op.drop_column('departure_transport_mode')
        batch_op.drop_column('arrival_transport_note')
        batch_op.drop_column('arrival_transport_cost_gbp')
        batch_op.drop_column('arrival_transport_mode')

    with op.batch_alter_table('trip_leg', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_leg_trip_id'))
        batch_op.drop_index(batch_op.f('ix_trip_leg_to_city_id'))
        batch_op.drop_index(batch_op.f('ix_trip_leg_from_city_id'))

    op.drop_table('trip_leg')
    # ### end Alembic commands ###
